### ISSUE TITLE
EF Core + Npgsql + NodaTime + linq2db - Cannot convert to DateTime

### ISSUE THREAD

**Issue by Evengard** [linq2db/linq2db.EntityFrameworkCore#178] opened 2021-09-16 15:19 UTC
I am having a weird bug when using Npgsql's NodaTime bindings. Each non-NodaTime binding just breaks with the following exceptions:
```
Cannot convert value '2021-09-16T18:14:14Z' to type 'System.DateTime': Object must implement IConvertible.
   at LinqToDB.Common.ConvertBuilder.ConvertDefault(Object value, Type conversionType)
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.ColumnReader.GetValue(IDataReader dataReader)
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IDataContext context, IQueryRunner queryRunner, IDataReader dataReader)
   at LinqToDB.Linq.QueryRunner.AsyncEnumeratorImpl`1.<MoveNextAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToArrayAsync>d__66`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at LinqToDB.AsyncExtensions.<ToArrayAsync>d__9`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

The same query when run through EF Core works just fine, but breaks through Linq2Db.

I've set up a simple repro:
<details>
  <summary>One-file repro</summary>
  
```csharp
using LinqToDB.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace L2DbBugRepro
{
    class Program
    {
        static async Task Main(string[] args)
        {
            await using (var ctx = new BlogContext())
            {
                await ctx.Database.EnsureDeletedAsync();
                await ctx.Database.EnsureCreatedAsync();

                ctx.Facts.Add(new Fact
                {
                    FactId = Guid.NewGuid(),
                    Date = DateTime.Now,
                });
                await ctx.SaveChangesAsync();
            }

            await using (var ctx = new BlogContext())
            {
                var facts = await ctx.Facts.ToArrayAsyncLinqToDB();
            }


        }
    }


    public class BlogContext : DbContext
    {
        public DbSet<Fact> Facts { get; set; }

        static ILoggerFactory ContextLoggerFactory
            => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder
                .UseNpgsql(@"Host=localhost;Username=root;Password=rootpass;Database=Testing", n => n.UseNodaTime())
    .EnableSensitiveDataLogging()
                .UseLoggerFactory(ContextLoggerFactory);

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        }
    }

    public class Fact
    {
        [Key]
        public Guid FactId { get; set; }

        public DateTime Date { get; set; }
        // Other fields redacted
    }
}
```
</details>

**Comment by sdanyliv** [comment] 2021-09-16 17:20
Try to initialise `MappingSchema.Default` with this code: https://github.com/linq2db/linq2db/blob/5dec345f6d597310c808d369f68fb88322c80f92/Tests/Linq/UserTests/Issue2560Tests.cs#L27-L49

**Comment by Evengard** [comment] 2021-09-16 17:30
Either I'm doing something incorrectly, or it doesn't help.
The repro with the suggested code throws the same exception:

<details>
<summary>Repro</summary>

```csharp
using LinqToDB.Common;
using LinqToDB.Data;
using LinqToDB.EntityFrameworkCore;
using LinqToDB.Mapping;
using LinqToDB.SqlQuery;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using NodaTime;
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using DataType = LinqToDB.DataType;

namespace L2DbBugRepro
{
    class Program
    {
        static async Task Main(string[] args)
        {
            await using (var ctx = new BlogContext())
            {
                await ctx.Database.EnsureDeletedAsync();
                await ctx.Database.EnsureCreatedAsync();

                ctx.Facts.Add(new Fact
                {
                    FactId = Guid.NewGuid(),
                    Date = DateTime.Now,
                });
                await ctx.SaveChangesAsync();
            }

            await using (var ctx = new BlogContext())
            {
                var facts = await ctx.Facts.ToArrayAsyncLinqToDB();
            }


        }
    }


    public class BlogContext : DbContext
    {
        public BlogContext()
        {
            var ms = new MappingSchema();
            ms.SetDataType(typeof(LocalDateTime), new SqlDataType(new DbDataType(typeof(DateTime), DataType.DateTime)));

            ms.SetConverter<LocalDateTime, DataParameter>(timeStamp =>
                new DataParameter
                {
                    Value = new DateTime(timeStamp.Year, timeStamp.Month, timeStamp.Day, timeStamp.Hour,
                        timeStamp.Minute, timeStamp.Second, timeStamp.Millisecond),
                    DataType = DataType.DateTime
                });

            ms.SetConverter<LocalDateTime, DateTime>(timeStamp =>
                new DateTime(timeStamp.Year, timeStamp.Month, timeStamp.Day, timeStamp.Hour,
                    timeStamp.Minute, timeStamp.Second, timeStamp.Millisecond));

            ms.SetValueToSqlConverter(typeof(LocalDateTime), (sb, dt, v) =>
            {
                var d = (LocalDateTime)v;
                var d1 = new DateTime(d.Year, d.Month, d.Day, d.Hour,
                    d.Minute, d.Second, d.Millisecond);

                sb.Append('\'').Append(d1.ToString()).Append('\'');
            }
            );
            MappingSchema.Default = ms;
        }

        public DbSet<Fact> Facts { get; set; }

        static ILoggerFactory ContextLoggerFactory
            => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder
                .UseNpgsql(@"Host=localhost;Username=root;Password=rootpass;Database=Testing", n => n.UseNodaTime())
    .EnableSensitiveDataLogging()
                .UseLoggerFactory(ContextLoggerFactory);

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        }
    }

    public class Fact
    {
        [Key]
        public Guid FactId { get; set; }

        public DateTime Date { get; set; }
        // Other fields redacted
    }
}

```
</details>

**Comment by sdanyliv** [comment] 2021-09-16 17:36
Not `MappingSchema.Default = ms`
But
```cs
var ms = MappingSchema.Default;
// initialisation code
```
And make this initialisation once in static constructor of `BlogContext`

**Comment by Evengard** [comment] 2021-09-16 17:53
I've actually tried that too, but the result was the same.
Reference:
<details>
<summary>Repro</summary>

```csharp
using LinqToDB.Common;
using LinqToDB.Data;
using LinqToDB.EntityFrameworkCore;
using LinqToDB.Mapping;
using LinqToDB.SqlQuery;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using NodaTime;
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using DataType = LinqToDB.DataType;

namespace L2DbBugRepro
{
    class Program
    {
        static async Task Main(string[] args)
        {
            await using (var ctx = new BlogContext())
            {
                await ctx.Database.EnsureDeletedAsync();
                await ctx.Database.EnsureCreatedAsync();

                ctx.Facts.Add(new Fact
                {
                    FactId = Guid.NewGuid(),
                    Date = DateTime.Now,
                });
                await ctx.SaveChangesAsync();
            }

            await using (var ctx = new BlogContext())
            {
                var facts = await ctx.Facts.ToArrayAsyncLinqToDB();
            }


        }
    }


    public class BlogContext : DbContext
    {
        static BlogContext()
        {
            var ms = MappingSchema.Default;
            ms.SetDataType(typeof(LocalDateTime), new SqlDataType(new DbDataType(typeof(DateTime), DataType.DateTime)));

            ms.SetConverter<LocalDateTime, DataParameter>(timeStamp =>
                new DataParameter
                {
                    Value = new DateTime(timeStamp.Year, timeStamp.Month, timeStamp.Day, timeStamp.Hour,
                        timeStamp.Minute, timeStamp.Second, timeStamp.Millisecond),
                    DataType = DataType.DateTime
                });

            ms.SetConverter<LocalDateTime, DateTime>(timeStamp =>
                new DateTime(timeStamp.Year, timeStamp.Month, timeStamp.Day, timeStamp.Hour,
                    timeStamp.Minute, timeStamp.Second, timeStamp.Millisecond));

            ms.SetValueToSqlConverter(typeof(LocalDateTime), (sb, dt, v) =>
            {
                var d = (LocalDateTime)v;
                var d1 = new DateTime(d.Year, d.Month, d.Day, d.Hour,
                    d.Minute, d.Second, d.Millisecond);

                sb.Append('\'').Append(d1.ToString()).Append('\'');
            }
            );
            MappingSchema.Default = ms;
        }

        public DbSet<Fact> Facts { get; set; }

        static ILoggerFactory ContextLoggerFactory
            => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Information));

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder
                .UseNpgsql(@"Host=localhost;Username=root;Password=rootpass;Database=Testing", n => n.UseNodaTime())
    .EnableSensitiveDataLogging()
                .UseLoggerFactory(ContextLoggerFactory);

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        }
    }

    public class Fact
    {
        [Key]
        public Guid FactId { get; set; }

        public DateTime Date { get; set; }
        // Other fields redacted
    }
}


```
</details>

**Comment by sdanyliv** [comment] 2021-09-16 17:58
Hm, which type has `Date` column in PostgreSQL database?

**Comment by Evengard** [comment] 2021-09-16 18:05
`timestamp without time zone`
<details>
<summary>screenshot</summary>

![изображение](https://user-images.githubusercontent.com/798735/133662436-279ab9bd-8646-431a-810c-b3486b9f4fb7.png)
</details>

**Comment by sdanyliv** [comment] 2021-09-16 18:09
Reproduced. Trying to figure out what happened.

**Comment by sdanyliv** [comment] 2021-09-16 18:24
Well I had bad assumptions. Npgsql propose `NodaTime.Instance` for conversion. So just correct your static constructor:
```cs
static BlogContext()
{
    var ms = MappingSchema.Default;

    ms.SetConverter<NodaTime.Instant, DataParameter>(timeStamp =>
        new DataParameter
        {
            Value = timeStamp.ToDateTimeUtc(),
            DataType = LinqToDB.DataType.DateTime
        });

    ms.SetConverter<NodaTime.Instant, DateTime>(timeStamp =>
        timeStamp.ToDateTimeUtc());
}
```

**Comment by sdanyliv** [comment] 2021-09-16 18:26
I even don't think that NodaTime.Instant -> DataParameter conversion is needed.

**Comment by Evengard** [comment] 2021-09-16 18:52
Well, using just
`ms.SetConverter<NodaTime.Instant, DateTime>(timeStamp =>
        timeStamp.ToDateTimeUtc());`
kind of worked, with one problem. Npgsql with EF Core sets Kind.Undefined for such DateTime's, but this sets Kind.Utc. I can see how to correct this though, although I'm afraid that might break something other.
Anyway, thanks!
Will something about this be included later in the linq2db codebase, or it is intended behaviour, and such MappingSchema is supposed to be applied in such case?

**Comment by sdanyliv** [comment] 2021-09-16 21:06
Actually yes. We don't want to add additional dependency to third party library. We have ideas how to do that dynamically, but  it needs efforts and design.

**Comment by Evengard** [comment] 2021-09-16 21:52
Is there a way to set theese mapping schemas per DbContext? Sure, I can do ctx.CreateLinqToDBConnection and set the mappings on it, but will it apply to indirect calls such as ToArrayAsyncLinqToDB on a DbSet?

**Comment by nathan-alden-sr** [comment] 2021-11-07 13:25
I'm having what I think is a similar issue but I haven't been able to configure `MappingSchema.Default` in a way that satisfies EF Core.

```cs
IQueryable<IdentityEmailAddressVerification> identityEmailAddressVerifications =
    _context
        .IdentityEmailAddressVerifications
        .Where(a => a.ExpirationTimestamp <= currentInstant); // NodaTime.Instant comparison

// var list = identityEmailAddressVerifications.ToList(); // This works fine
await identityEmailAddressVerifications.DeleteAsync(context.CancellationToken); // This doesn't--exception!
```

In my context's static constructor:

```cs
MappingSchema.Default.SetConverter<Instant, DateTime>(instant => instant.ToDateTimeUtc());
```

**Comment by sdanyliv** [comment] 2021-11-07 13:31
Probably you forgot to call ToLinqToDB(). Because it is EF Core exception.

**Comment by nathan-alden-sr** [comment] 2021-11-07 13:34
Delete changed to this:

```cs
await identityEmailAddressVerifications.ToLinqToDB().DeleteAsync(context.CancellationToken);
```

Gave this new exception:

> Quartz.SchedulerException: Job threw an unhandled exception.
 ---> LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsException: Can not find private property 'RelationalQueryContextFactory._dependencies' in current EFCore Version.
   at LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsImplDefault.GetCurrentContext(IQueryable query)
   at LinqToDB.EntityFrameworkCore.LinqToDBForEFTools.ToLinqToDB[T](IQueryable`1 query)

**Comment by sdanyliv** [comment] 2021-11-07 13:37
It is because you use latest EF Core 6. Will check which providers are ready for this version.

**Comment by sdanyliv** [comment] 2021-11-08 20:57
Check latest version that have released today. It supports EF Core 6.0.0.

**Comment by nathan-alden-sr** [comment] 2021-11-09 02:24
I wasn't able to get the new version working. I don't get the reflection error. Here's the code:

```cs
var toDelete = _context.IdentityEmailAddressVerifications.Where(a => a.Id == requestModel.Id); // Both Ids are Guids
_ = await toDelete.DeleteAsync(cancellationToken);
```

Entity:

```cs
public sealed class IdentityEmailAddressVerification
{
    public Guid Id { get; set; }
    public string EmailAddress { get; set; } = default!;
    public Instant CreationTimestamp { get; set; }
    public Instant ExpirationTimestamp { get; set; }
}
```

Static context constructor:
```cs
static MyContext()
{
    MappingSchema.Default.SetConverter<Instant, DateTime>(instant => instant.ToDateTimeUtc());
    MappingSchema.Default.SetConverter<Instant, DateTimeOffset>(instant => instant.ToDateTimeOffset());
}
```

**Comment by nathan-alden-sr** [comment] 2021-11-09 02:26
It worked! Thank you very much for the quick update to EF Core 6. 👍

**Comment by Evengard** [comment] 2021-11-10 03:35
Another related problem, except this one seems to be more tricky.

Consider a model like that:
```csharp
public class Profile
{
[Key]
public Guid Id {get; set;}
[Column(TypeName = "jsonb")]
public AdditionalInfo Info {get; set;}
}

public class AdditionalInfo
{
public DateTime BirthDate {get; set;}
public string Note {get; set;}
}
```

And a simple query like this:
```csharp
ctx.Profiles.ToArrayAsyncLinqToDB();
```
Throws an exception:
```
Unhandled exception. LinqToDB.Common.LinqToDBConvertException: Cannot convert value '{"Note": "smth", "BirthDate": "2021-11-10T06:31:30.7873149+03:00"}' to type 'L2DbBugRepro.AdditionalInfo'
 ---> System.InvalidCastException: Invalid cast from 'System.String' to 'L2DbBugRepro.AdditionalInfo'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at LinqToDB.Common.ConvertBuilder.ConvertDefault(Object value, Type conversionType)
   --- End of inner exception stack trace ---
   at LinqToDB.Common.ConvertBuilder.ConvertDefault(Object value, Type conversionType)
   at lambda_method229(Closure , IDataReader )
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.ColumnReader.GetValue(IDataReader dataReader)
   at lambda_method227(Closure , IQueryRunner , IDataReader )
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IDataContext context, IQueryRunner queryRunner, IDataReader dataReader)
   at LinqToDB.Linq.QueryRunner.AsyncEnumeratorImpl`1.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken token)
```

While when using EF Core, I get the jsonb field converted to the said `AdditionalInfo` class.
This is leveraging this feature: https://www.npgsql.org/efcore/mapping/json.html

**Comment by Evengard** [comment] 2021-11-10 03:46
I've managed to work it around with smth like this in my dbcontext:
```csharp
this.CreateLinqToDbConnection().MappingSchema.SetConverter<string, BirthdayInfo>(json => JsonSerializer.Deserialize<BirthdayInfo>(json));
```
but is there a way to pull that automatically, like EF Core does?

**Comment by sdanyliv** [comment] 2021-11-10 05:17
Will prepare something like this. Your approach is wrong, better to use MappingSchema.Default right now.

**Comment by Evengard** [comment] 2021-11-10 05:24
Is there actually a way to assign a specific mappingcontext for a specific EF dbcontext? I really don't want to pollute the global default mappingschema with bindings specific to this exact dbcontext.

**Comment by sdanyliv** [comment] 2021-11-10 05:27
No way right now. Use global mapping schema temporary, otherwise you will loose performance.

**Comment by Evengard** [comment] 2021-11-22 11:02
I've managed to work it around for now with smth crazy like that:
```csharp
private static void SetJsonConverter<Td>()
{
    MappingSchema.Default.SetConverter<string, Td>((s) => JsonSerializer.Deserialize<Td>(s));
}

static DbCtx()
{
    var method = typeof(AbstractDbContext<T>).GetMethod("SetJsonConverter", BindingFlags.Static | BindingFlags.NonPublic);
    // DB_SET_TYPES is constructed by scanning the used DbSets by the context
    DB_SET_TYPES
        .Union(DERIVED_ENTITIES)
        .SelectMany(t => t.GetProperties())
        .Where(p => p.GetCustomAttribute<ColumnAttribute>()?.TypeName == "jsonb")
        .Select(p => p.PropertyType)
        .Apply(t =>
        {
            var finalMethod = method.MakeGenericMethod(t);
            finalMethod.Invoke(null, null);
        });
}
```
It is quite hacky but seems to work...

**Comment by MaceWindu** [comment] 2023-02-26 14:20
Closing as answered.

Would add that there is no need to modify global `MappingSchema.Default` with new `AddMappingSchema` configuration API in latest release: you can configure separate mapping schema.

**Closed by MaceWindu** 2023-02-26 14:20 UTC
