### ISSUE TITLE
Using EF Core type converters

### ISSUE THREAD

**Issue by Kirill-Maurin** [linq2db/linq2db.EntityFrameworkCore#21] opened 2020-01-24 07:53 UTC
Current version don't support EF Core type converters.
I have to write each converter twice
1. EF Core for migrations
2. Linq2db for queries

**Comment by sdanyliv** [comment] 2020-01-24 08:06
Not familiar with EF, could you give me additional details?

**Comment by Kirill-Maurin** [comment] 2020-01-24 08:21
`    public readonly struct Id<TEntity, TKey> : IEquatable<Id<TEntity, TKey>> where TEntity : IEntity<TKey>
    {
        public Id(TKey id) => Value = id;
        public TKey Value { get; }
        public static implicit operator TKey(Id<TEntity, TKey> id) => id.Value;
        public override string ToString() => Value?.ToString();
        public bool Equals(Id<TEntity, TKey> other) => EqualityComparer<TKey>.Default.Equals(Value, other.Value);
        public override bool Equals(object obj) => obj is Id<TEntity, TKey> other && Equals(other);
        public override int GetHashCode() => EqualityComparer<TKey>.Default.GetHashCode(Value);
    }`

**Comment by sdanyliv** [comment] 2020-01-24 08:25
How you define converter for EF Core?

**Comment by Kirill-Maurin** [comment] 2020-01-24 08:26
Converter
```cs
    public sealed class IdValueConverter<TKey, TEntity> : ValueConverter<Id<TEntity, TKey>, TKey>
        where TEntity : IEntity<TKey>
    {
        public IdValueConverter(ConverterMappingHints mappingHints = null)
            : base(id => id.Value, key => new Id<TEntity, TKey>(key)) { }
    }
```

**Comment by sdanyliv** [comment] 2020-01-24 08:28
Any real example with model builder?

**Comment by Kirill-Maurin** [comment] 2020-01-24 08:28
Selector
```cs
    public sealed class IdValueConverterSelector : ValueConverterSelector
    {
        public IdValueConverterSelector([System.Diagnostics.CodeAnalysis.NotNull] ValueConverterSelectorDependencies dependencies) : base(dependencies)
        {
        }

        public override IEnumerable<ValueConverterInfo> Select(Type modelClrType, Type providerClrType = null)
        {
            var baseConverters = base.Select(modelClrType, providerClrType);
            foreach (var converter in baseConverters)
                yield return converter;

            modelClrType = Unwrap(modelClrType);
            providerClrType = Unwrap(providerClrType);

            if (!modelClrType.IsGenericType)
                yield break;

            if (modelClrType.GetGenericTypeDefinition() != typeof(Id<,>))
                yield break;

            var t = modelClrType.GetGenericArguments();
            var key = t[1];
            providerClrType ??= key;
            if (key != providerClrType)
                yield break;

            var ct = typeof(IdValueConverter<,>).MakeGenericType(key, t[0]);
            yield return new ValueConverterInfo
            (
                modelClrType, 
                providerClrType, 
                i => (ValueConverter)Activator.CreateInstance(ct, i.MappingHints)
            );

            static Type Unwrap(Type type) => type == null ? null : Nullable.GetUnderlyingType(type) ?? type;
        }
    }
```

**Comment by Kirill-Maurin** [comment] 2020-01-24 08:32
DbContext registration
```cs
            services.AddDbContext<AuthorizationContext>
            (
                options => options
                    .ReplaceService<IValueConverterSelector, IdValueConverterSelector>()
                    .UseNpgsql(Configuration.GetConnectionString("DbConnection"),
                        b => b.MigrationsAssembly(typeof(AuthorizationContext).Assembly.FullName))
            );
```

**Comment by Kirill-Maurin** [comment] 2020-01-24 08:34
Model 
```cs
    public class Subdivision : IEntity<long>
    {
        long IEntity<long>.Id => Id;
        public Id<Subdivision, long> Id { get; set; }
        public Guid PermanentId { get; set; }
        public Id<Subdivision, long>? ParentId { get; set; }
        public Id<LegalEntity, long> LegalEntityId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool? IsDeleted { get; set; }
    }
```

**Comment by Kirill-Maurin** [comment] 2020-01-24 08:35
IEntity interface
```cs
    public interface IEntity<T>
    {
        /// <summary>
        /// Неизменяемый идентификатор сущности. Может быть привязан к конкретному хранилищу данных
        /// </summary>
        T Id { get; }
    }
```

**Comment by sdanyliv** [comment] 2020-01-24 09:15
Looks like i have enough information to play with.

**Comment by sdanyliv** [comment] 2020-01-28 11:21
Which version of EF Core do you use?

**Comment by Kirill-Maurin** [comment] 2020-01-30 13:16
> Which version of EF Core do you use?

3.1

**Comment by sdanyliv** [comment] 2020-01-30 14:07
@Kirill-Maurin, which linq queries fail? I'm to reproduce to make general solution.
This one works
```cs
	var ef   = ctx.Subdivisions.Where(s => s.Id == 1).ToArray();
	var ltdb = ctx.Subdivisions.ToLinqToDB().Where(s => s.Id == 1).ToArray();
```

**Comment by sdanyliv** [comment] 2020-01-30 16:43
@Kirill-Maurin, we just released new version with important bug-fixes. Your request will be fixed as soon as we create appropriate reproducible converter example.

**Comment by Kirill-Maurin** [comment] 2020-01-31 09:30
> which linq queries fail?

Method InsertWithIdentityAsync fail when entity has generic Id<> properties except primary key
Error message:
```
System.NotSupportedException : The CLR type Core.Id`2[Storage.Object,System.Int64] isn't natively supported by Npgsql or your PostgreSQL. To use it with a PostgreSQL composite you need to specify DataTypeName or to map it, please refer to the documentation.
   at Npgsql.TypeMapping.ConnectorTypeMapper.GetByClrType(Type type) in C:\projects\npgsql\src\Npgsql\TypeMapping\ConnectorTypeMapper.cs:line 125
   at Npgsql.NpgsqlParameter.ResolveHandler(ConnectorTypeMapper typeMapper) in C:\projects\npgsql\src\Npgsql\NpgsqlParameter.cs:line 490
   at Npgsql.NpgsqlCommand.ValidateParameters(ConnectorTypeMapper typeMapper) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 765
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1094
   at Npgsql.NpgsqlCommand.ExecuteScalar(Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1022
   at LinqToDB.Data.DataConnection.ExecuteScalarAsync(CancellationToken cancellationToken) in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.Async.cs:line 293
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteScalarAsync(CancellationToken cancellationToken) in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:line 599
   at LinqToDB.Linq.QueryRunner.ScalarQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, CancellationToken cancellationToken) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 742
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken token) in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 89
   at LinqToDB.LinqExtensions.InsertWithIdentityAsync[T](ITable`1 target, Expression`1 setter, CancellationToken token) in C:\projects\linq2db\Source\LinqToDB\LinqExtensions.cs:line 1059
   at LinqToDB.LinqExtensions.InsertWithInt64IdentityAsync[T](ITable`1 target, Expression`1 setter, CancellationToken token) in 
```

**Comment by Kirill-Maurin** [comment] 2020-01-31 09:46
Dirty fix for our projects:
https://gist.github.com/Kirill-Maurin/8dfbe8b3584cda2c01207e6e9c47a66f

**Comment by BalassaMarton** [comment] 2020-01-31 10:25
Let me give you a simpler example

```cs
public class Entity {
    public Guid Id { get; set; }
    public IDictionary<string, string> CustomAttributes { get; set; }
}
```
```cs
    modelBuilder.Entity<Entity>(
        entity => {
            entity.Property(x => x.CustomAttributes)
                .HasConversion(
                    dictionary => JsonConvert.SerializeObject(dictionary),
                    json => JsonConvert.DeserializeObject<Dictionary<string, string>>(json)
                );
        }
    );
```
```cs
    db.Set<Entity>.ToLinqToDB().ToList(); // <--- throws LinqToDBConvertException
```

**Closed** 2020-02-01 12:44 UTC

**Comment by sdanyliv** [comment] 2020-02-01 12:48
@BalassaMarton, such conversion is not supported. Linq2db do not handle Member by Member conversions. But it is doable, will add this in later.

**Comment by dgoldm** [comment] 2020-03-25 10:00
> 
> 
> such conversion is not supported. Linq2db do not handle Member by Member conversions. But it is doable, will add this later.

This is preventing me from using linq2db in my EF Core project. Is there a workaround I could use until you add support for this?
